package mx.random.constants{
	import mx.collections.ArrayCollection;
	
	[Bindable]
	public class Countries{
		
		public static var NationalStates:ArrayCollection = new ArrayCollection([
			{ label:"Seleccionar", 			value: "00"},
			{ label:"Aguascalientes", 		value: "AS"},
			{ label:"Baja California", 		value: "BC"},
			{ label:"Baja California Sur", 	value: "BS"},
			{ label:"Campeche", 			value: "CC"},
			{ label:"Chiapas",	 			value: "CS"},
			{ label:"Chihuahua", 			value: "CH"},
			{ label:"Coahuila", 			value: "CL"},
			{ label:"Colima", 				value: "CM"},
			{ label:"Distrito Federal", 	value: "DF"},
			{ label:"Durango", 				value: "DG"},
			{ label:"Guanajuato", 			value: "GT"},
			{ label:"Guerrero", 			value: "GR"},
			{ label:"Hidalgo", 				value: "HG"},
			{ label:"Jalisco", 				value: "JC"},
			{ label:"Estado de México", 	value: "MC"},
			{ label:"Michoacán", 			value: "MN"},
			{ label:"Morelos", 				value: "MS"},
			{ label:"Nayarit", 				value: "NT"},
			{ label:"Nuevo León", 			value: "NL"},
			{ label:"Oaxaca", 				value: "OC"},
			{ label:"Puebla", 				value: "PL"},
			{ label:"Querétaro", 			value: "QT"},
			{ label:"Quintana Roo", 		value: "QR"},
			{ label:"San Luis Potosí", 		value: "SP"},
			{ label:"Sinaloa", 				value: "SL"},
			{ label:"Sonora", 				value: "SR"},
			{ label:"Tabasco", 				value: "TC"},
			{ label:"Tamaulipas", 			value: "TS"},
			{ label:"Tlaxcala", 			value: "TL"},
			{ label:"Veracruz", 			value: "VZ"},
			{ label:"Yucatán", 				value: "YN"},
			{ label:"Zacatecas", 			value: "ZS"}
			]);
		
		public static var International:ArrayCollection = new ArrayCollection([
			{ value: "00", label: "Select" },
        	{ value: "AD", label: "Andorra" },
   			{ value: "AE", label: "United Arab Emirates" },
		   	{ value: "AF", label: "Afghanistan" },
		   	{ value: "AG", label: "Antigua & Barbuda" },
		   	{ value: "AI", label: "Anguilla" },
		   	{ value: "AL", label: "Albania" },
		   	{ value: "AM", label: "Armenia" },
		   	{ value: "AN", label: "Netherlands Antilles" },
		   	{ value: "AO", label: "Angola" },
		   	{ value: "AQ", label: "Antarctica" },
		   	{ value: "AR", label: "Argentina" },
		   	{ value: "AS", label: "American Samoa" },
		   	{ value: "AT", label: "Austria" },
		   	{ value: "AU", label: "Australia" },
		   	{ value: "AW", label: "Aruba" },
		   	{ value: "AZ", label: "Azerbaijan" },
		   	{ value: "BA", label: "Bosnia and Herzegovina" },
		   	{ value: "BB", label: "Barbados" },
		   	{ value: "BD", label: "Bangladesh" },
		   	{ value: "BE", label: "Belgium" },
		   	{ value: "BF", label: "Burkina Faso" },
		   	{ value: "BG", label: "Bulgaria" },
		   	{ value: "BH", label: "Bahrain" },
		   	{ value: "BI", label: "Burundi" },
		   	{ value: "BJ", label: "Benin" },
		   	{ value: "BM", label: "Bermuda" },
		   	{ value: "BN", label: "Brunei Darussalam" },
		   	{ value: "BO", label: "Bolivia" },
		   	{ value: "BR", label: "Brazil" },
		   	{ value: "BS", label: "Bahama" },
		   	{ value: "BT", label: "Bhutan" },
		   	{ value: "BU", label: "Burma (no longer exists)" },
		   	{ value: "BV", label: "Bouvet Island" },
		   	{ value: "BW", label: "Botswana" },
		   	{ value: "BY", label: "Belarus" },
		   	{ value: "BZ", label: "Belize" },
		   	{ value: "CA", label: "Canada" },
		   	{ value: "CC", label: "Cocos (Keeling) Islands" },
		   	{ value: "CF", label: "Central African Republic" },
		   	{ value: "CG", label: "Congo" },
		   	{ value: "CH", label: "Switzerland" },
		   	{ value: "CI", label: "C&ocirc;te D'ivoire (Ivory Coast)" },
		   	{ value: "CK", label: "Cook Iislands" },
		   	{ value: "CL", label: "Chile" },
		   	{ value: "CM", label: "Cameroon" },
		   	{ value: "CN", label: "China" },
		   	{ value: "CO", label: "Colombia" },
		   	{ value: "CR", label: "Costa Rica" },
		   	{ value: "CS", label: "Czechoslovakia (no longer exists)" },
		   	{ value: "CU", label: "Cuba" },
		   	{ value: "CV", label: "Cape Verde" },
		   	{ value: "CX", label: "Christmas Island" },
		   	{ value: "CY", label: "Cyprus" },
		   	{ value: "CZ", label: "Czech Republic" },
		   	{ value: "DD", label: "German Democratic Republic (no longer exists)" },
		   	{ value: "DE", label: "Germany" },
		   	{ value: "DJ", label: "Djibouti" },
		   	{ value: "DK", label: "Denmark" },
		   	{ value: "DM", label: "Dominica" },
		   	{ value: "DO", label: "Dominican Republic" },
		   	{ value: "DZ", label: "Algeria" },
		   	{ value: "EC", label: "Ecuador" },
		   	{ value: "EE", label: "Estonia" },
		   	{ value: "EG", label: "Egypt" },
		   	{ value: "EH", label: "Western Sahara" },
		   	{ value: "ER", label: "Eritrea" },
		   	{ value: "ES", label: "Spain" },
		   	{ value: "ET", label: "Ethiopia" },
		   	{ value: "FI", label: "Finland" },
		   	{ value: "FJ", label: "Fiji" },
		   	{ value: "FK", label: "Falkland Islands (Malvinas)" },
		   	{ value: "FM", label: "Micronesia" },
		   	{ value: "FO", label: "Faroe Islands" },
		   	{ value: "FR", label: "France" },
		   	{ value: "FX", label: "France, Metropolitan" },
		   	{ value: "GA", label: "Gabon" },
		   	{ value: "GB", label: "United Kingdom (Great Britain)" },
		   	{ value: "GD", label: "Grenada" },
		   	{ value: "GE", label: "Georgia" },
		   	{ value: "GF", label: "French Guiana" },
		   	{ value: "GH", label: "Ghana" },
		   	{ value: "GI", label: "Gibraltar" },
		   	{ value: "GL", label: "Greenland" },
		   	{ value: "GM", label: "Gambia" },
		   	{ value: "GN", label: "Guinea" },
		   	{ value: "GP", label: "Guadeloupe" },
		   	{ value: "GQ", label: "Equatorial Guinea" },
		   	{ value: "GR", label: "Greece" },
		   	{ value: "GS", label: "South Georgia and the South Sandwich Islands" },
		   	{ value: "GT", label: "Guatemala" },
		   	{ value: "GU", label: "Guam" },
		   	{ value: "GW", label: "Guinea-Bissau" },
		   	{ value: "GY", label: "Guyana" },
		   	{ value: "HK", label: "Hong Kong" },
		   	{ value: "HM", label: "Heard & McDonald Islands" },
		   	{ value: "HN", label: "Honduras" },
		   	{ value: "HR", label: "Croatia" },
		   	{ value: "HT", label: "Haiti" },
		   	{ value: "HU", label: "Hungary" },
		   	{ value: "ID", label: "Indonesia" },
		   	{ value: "IE", label: "Ireland" },
		   	{ value: "IL", label: "Israel" },
		   	{ value: "IN", label: "India" },
		   	{ value: "IO", label: "British Indian Ocean Territory" },
		   	{ value: "IQ", label: "Iraq" },
		   	{ value: "IR", label: "Islamic Republic of Iran" },
		   	{ value: "IS", label: "Iceland" },
		   	{ value: "IT", label: "Italy" },
		   	{ value: "JM", label: "Jamaica" },
		   	{ value: "JO", label: "Jordan" },
		   	{ value: "JP", label: "Japan" },
		   	{ value: "KE", label: "Kenya" },
		   	{ value: "KG", label: "Kyrgyzstan" },
		   	{ value: "KH", label: "Cambodia" },
		   	{ value: "KI", label: "Kiribati" },
		   	{ value: "KM", label: "Comoros" },
		   	{ value: "KN", label: "St. Kitts and Nevis" },
		   	{ value: "KP", label: "Korea, Democratic People's Republic of" },
		   	{ value: "KR", label: "Korea, Republic of" },
		   	{ value: "KW", label: "Kuwait" },
		   	{ value: "KY", label: "Cayman Islands" },
		   	{ value: "KZ", label: "Kazakhstan" },
		   	{ value: "LA", label: "Lao People's Democratic Republic" },
		   	{ value: "LB", label: "Lebanon" },
		   	{ value: "LC", label: "Saint Lucia" },
		   	{ value: "LI", label: "Liechtenstein" },
		   	{ value: "LK", label: "Sri Lanka" },
		   	{ value: "LR", label: "Liberia" },
		   	{ value: "LS", label: "Lesotho" },
		   	{ value: "LT", label: "Lithuania" },
		   	{ value: "LU", label: "Luxembourg" },
		   	{ value: "LV", label: "Latvia" },
		   	{ value: "LY", label: "Libyan Arab Jamahiriya" },
		   	{ value: "MA", label: "Morocco" },
		   	{ value: "MC", label: "Monaco" },
		   	{ value: "MD", label: "Moldova, Republic of" },
		   	{ value: "MG", label: "Madagascar" },
		   	{ value: "MH", label: "Marshall Islands" },
		   	{ value: "ML", label: "Mali" },
		   	{ value: "MN", label: "Mongolia" },
		   	{ value: "MM", label: "Myanmar" },
		   	{ value: "MO", label: "Macau" },
		   	{ value: "MP", label: "Northern Mariana Islands" },
		   	{ value: "MQ", label: "Martinique" },
		   	{ value: "MR", label: "Mauritania" },
		   	{ value: "MS", label: "Monserrat" },
		   	{ value: "MT", label: "Malta" },
		   	{ value: "MU", label: "Mauritius" },
		   	{ value: "MV", label: "Maldives" },
		   	{ value: "MW", label: "Malawi" },
		   	{ value: "MX", label: "Mexico" },
		   	{ value: "MY", label: "Malaysia" },
		   	{ value: "MZ", label: "Mozambique" },
		   	{ value: "NA", label: "Namibia" },
		   	{ value: "NC", label: "New Caledonia" },
		   	{ value: "NE", label: "Niger" },
		   	{ value: "NF", label: "Norfolk Island" },
		   	{ value: "NG", label: "Nigeria" },
		   	{ value: "NI", label: "Nicaragua" },
		   	{ value: "NL", label: "Netherlands" },
		   	{ value: "NO", label: "Norway" },
		   	{ value: "NP", label: "Nepal" },
		   	{ value: "NR", label: "Nauru" },
		   	{ value: "NT", label: "Neutral Zone (no longer exists)" },
		   	{ value: "NU", label: "Niue" },
		   	{ value: "NZ", label: "New Zealand" },
		   	{ value: "OM", label: "Oman" },
		   	{ value: "PA", label: "Panama" },
		   	{ value: "PE", label: "Peru" },
		   	{ value: "PF", label: "French Polynesia" },
		   	{ value: "PG", label: "Papua New Guinea" },
		   	{ value: "PH", label: "Philippines" },
		   	{ value: "PK", label: "Pakistan" },
		   	{ value: "PL", label: "Poland" },
		   	{ value: "PM", label: "St. Pierre & Miquelon" },
		   	{ value: "PN", label: "Pitcairn" },
		   	{ value: "PR", label: "Puerto Rico" },
		   	{ value: "PT", label: "Portugal" },
		   	{ value: "PW", label: "Palau" },
		   	{ value: "PY", label: "Paraguay" },
		   	{ value: "QA", label: "Qatar" },
		   	{ value: "RE", label: "R&eacute;union" },
		   	{ value: "RO", label: "Romania" },
		   	{ value: "RU", label: "Russian Federation" },
		   	{ value: "RW", label: "Rwanda" },
		   	{ value: "SA", label: "Saudi Arabia" },
		   	{ value: "SB", label: "Solomon Islands" },
		   	{ value: "SC", label: "Seychelles" },
		   	{ value: "SD", label: "Sudan" },
		   	{ value: "SE", label: "Sweden" },
		   	{ value: "SG", label: "Singapore" },
		   	{ value: "SH", label: "St. Helena" },
		   	{ value: "SI", label: "Slovenia" },
		   	{ value: "SJ", label: "Svalbard & Jan Mayen Islands" },
		   	{ value: "SK", label: "Slovakia" },
		   	{ value: "SL", label: "Sierra Leone" },
		   	{ value: "SM", label: "San Marino" },
		   	{ value: "SN", label: "Senegal" },
		   	{ value: "SO", label: "Somalia" },
		   	{ value: "SR", label: "Suriname" },
		   	{ value: "ST", label: "Sao Tome & Principe" },
		   	{ value: "SU", label: "Union of Soviet Socialist Republics (no longer exists)" },
		   	{ value: "SV", label: "El Salvador" },
		   	{ value: "SY", label: "Syrian Arab Republic" },
		   	{ value: "SZ", label: "Swaziland" },
		   	{ value: "TC", label: "Turks & Caicos Islands" },
		   	{ value: "TD", label: "Chad" },
		   	{ value: "TF", label: "French Southern Territories" },
		   	{ value: "TG", label: "Togo" },
		   	{ value: "TH", label: "Thailand" },
		   	{ value: "TJ", label: "Tajikistan" },
		   	{ value: "TK", label: "Tokelau" },
		   	{ value: "TM", label: "Turkmenistan" },
		   	{ value: "TN", label: "Tunisia" },
		   	{ value: "TO", label: "Tonga" },
		   	{ value: "TP", label: "East Timor" },
		   	{ value: "TR", label: "Turkey" },
		   	{ value: "TT", label: "Trinidad & Tobago" },
		   	{ value: "TV", label: "Tuvalu" },
		   	{ value: "TW", label: "Taiwan, Province of China" },
		   	{ value: "TZ", label: "Tanzania, United Republic of" },
		   	{ value: "UA", label: "Ukraine" },
		   	{ value: "UG", label: "Uganda" },
		   	{ value: "UM", label: "United States Minor Outlying Islands" },
		   	{ value: "US", label: "United States of America" },
		   	{ value: "UY", label: "Uruguay" },
		   	{ value: "UZ", label: "Uzbekistan" },
		   	{ value: "VA", label: "Vatican City State (Holy See)" },
		   	{ value: "VC", label: "St. Vincent & the Grenadines" },
		   	{ value: "VE", label: "Venezuela" },
		   	{ value: "VG", label: "British Virgin Islands" },
		   	{ value: "VI", label: "United States Virgin Islands" },
		   	{ value: "VN", label: "Viet Nam" },
		   	{ value: "VU", label: "Vanuatu" },
		   	{ value: "WF", label: "Wallis & Futuna Islands" },
		   	{ value: "WS", label: "Samoa" },
		   	{ value: "YD", label: "Democratic Yemen (no longer exists)" },
		   	{ value: "YE", label: "Yemen" },
		   	{ value: "YT", label: "Mayotte" },
		   	{ value: "YU", label: "Yugoslavia" },
		   	{ value: "ZA", label: "South Africa" },
		   	{ value: "ZM", label: "Zambia" },
		   	{ value: "ZR", label: "Zaire" },
		   	{ value: "ZW", label: "Zimbabwe" },
		   	{ value: "ZZ", label: "Otra" }
			]);
		
		public function Countries(){
		}		
	}}